# Security, token setting
tokenPrivateKey: aswkz234gyucxz65gre2d9df43508dfudgyu
# Database connection setting
# ===================================

database:
  timezone: +09:00
  dialect: mysql
  enableSyncTable: false

  development: # Development database
    host: localhost
    port: 3306
    database: dadi_manager
    username: root
    password: tuan123445

  production: # Production database
    host: localhost
    port: 3306
    database: dadi_manager
    username: root
    password: tuan123445
